---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anbae-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anbae-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: anbae
  labels:
    app: anbae
spec:
  volumes:
    - name: anbae-pv-storage
      persistentVolumeClaim:
        claimName: anbae-pv-claim
  containers:
    - name: anbae-big-data-course
      image: anderslaunerbaek/anbae-big-data-course:latest
      imagePullPolicy: Always
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/root/code"
          name: anbae-pv-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: hdfs-cli
  labels:
    app: hdfs-cli
spec:
  containers:
    - name: hdfs-cli
      image: apache/hadoop:3
      imagePullPolicy: Always
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/opt/hadoop/code"
          name: anbae-pv-storage
      env:
        - name: HADOOP_USER_NAME
          value: "stackable"
